// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A cluster in a private cloud.
public struct Cluster: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The resource name of this cluster.
  /// Resource names are schemeless URIs that follow the conventions in
  /// https://cloud.google.com/apis/design/resource_names.
  /// For example:
  /// `projects/my-project/locations/us-central1-a/privateClouds/my-cloud/clusters/my-cluster`
  public var name: Swift.String = Swift.String()

  /// Output only. Creation time of this resource.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Last update time of this resource.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. State of the resource.
  public var state: Cluster.State = Cluster.State()

  /// Output only. True if the cluster is a management cluster; false otherwise.
  /// There can only be one management cluster in a private cloud
  /// and it has to be the first one.
  public var management: Swift.Bool = Swift.Bool()

  /// Optional. Configuration of the autoscaling applied to this cluster.
  public var autoscalingSettings: AutoscalingSettings? = nil

  /// Output only. System-generated unique identifier for the resource.
  public var uid: Swift.String = Swift.String()

  /// Required. The map of cluster node types in this cluster, where the key is
  /// canonical identifier of the node type (corresponds to the `NodeType`).
  public var nodeTypeConfigs: [Swift.String: NodeTypeConfig] = [:]

  /// Optional. Configuration of a stretched cluster. Required for clusters that
  /// belong to a STRETCHED private cloud.
  public var stretchedClusterConfig: StretchedClusterConfig? = nil

  /// Initialize a new instance of `Cluster`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Cluster().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Enum State defines possible states of private cloud clusters.
  public enum State: Codable, Equatable, Sendable {
    /// The default value. This value should never be used.
    case unspecified
    /// The Cluster is operational and can be used by the user.
    case active
    /// The Cluster is being deployed.
    case creating
    /// Adding or removing of a node to the cluster, any other cluster specific
    /// updates.
    case updating
    /// The Cluster is being deleted.
    case deleting
    /// The Cluster is undergoing maintenance, for example: a failed node is
    /// getting replaced.
    case repairing
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .active: return 1
      case .creating: return 2
      case .updating: return 3
      case .deleting: return 4
      case .repairing: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .active: return "ACTIVE"
      case .creating: return "CREATING"
      case .updating: return "UPDATING"
      case .deleting: return "DELETING"
      case .repairing: return "REPAIRING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "ACTIVE": self = .active
      case "CREATING": self = .creating
      case "UPDATING": self = .updating
      case "DELETING": self = .deleting
      case "REPAIRING": self = .repairing
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .active
      case 2: self = .creating
      case 3: self = .updating
      case 4: self = .deleting
      case 5: self = .repairing
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .active: return try container.encode(1)
      case .creating: return try container.encode(2)
      case .updating: return try container.encode(3)
      case .deleting: return try container.encode(4)
      case .repairing: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmwareengine.v1.Cluster"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
