// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// External access firewall rules for filtering incoming traffic destined to
/// `ExternalAddress` resources.
public struct ExternalAccessRule: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The resource name of this external access rule.
  /// Resource names are schemeless URIs that follow the conventions in
  /// https://cloud.google.com/apis/design/resource_names.
  /// For example:
  /// `projects/my-project/locations/us-central1/networkPolicies/my-policy/externalAccessRules/my-rule`
  public var name: Swift.String = Swift.String()

  /// Output only. Creation time of this resource.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Last update time of this resource.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// User-provided description for this external access rule.
  public var description: Swift.String = Swift.String()

  /// External access rule priority, which determines the external access rule to
  /// use when multiple rules apply. If multiple rules have the same priority,
  /// their ordering is non-deterministic. If specific ordering is required,
  /// assign unique priorities to enforce such ordering. The external access rule
  /// priority is an integer from 100 to 4096, both inclusive. Lower integers
  /// indicate higher precedence. For example, a rule with priority `100` has
  /// higher precedence than a rule with priority `101`.
  public var priority: Swift.Int32 = Swift.Int32()

  /// The action that the external access rule performs.
  public var action: ExternalAccessRule.Action = ExternalAccessRule.Action()

  /// The IP protocol to which the external access rule applies. This value can
  /// be one of the following three protocol strings (not case-sensitive):
  /// `tcp`, `udp`, or `icmp`.
  public var ipProtocol: Swift.String = Swift.String()

  /// If source ranges are specified, the external access rule applies only to
  /// traffic that has a source IP address in these ranges. These ranges can
  /// either be expressed in the CIDR format or as an IP address. As only inbound
  /// rules are supported, `ExternalAddress` resources cannot be the source IP
  /// addresses of an external access rule. To match all source addresses,
  /// specify `0.0.0.0/0`.
  public var sourceIpRanges: [ExternalAccessRule.IpRange] = []

  /// A list of source ports to which the external access rule applies. This
  /// field is only applicable for the UDP or TCP protocol.
  /// Each entry must be either an integer or a range. For example: `["22"]`,
  /// `["80","443"]`, or `["12345-12349"]`. To match all source ports, specify
  /// `["0-65535"]`.
  public var sourcePorts: [Swift.String] = []

  /// If destination ranges are specified, the external access rule applies only
  /// to the traffic that has a destination IP address in these ranges. The
  /// specified IP addresses must have reserved external IP addresses in the
  /// scope of the parent network policy. To match all external IP addresses in
  /// the scope of the parent network policy, specify `0.0.0.0/0`. To match a
  /// specific external IP address, specify it using the
  /// `IpRange.external_address` property.
  public var destinationIpRanges: [ExternalAccessRule.IpRange] = []

  /// A list of destination ports to which the external access rule applies. This
  /// field is only applicable for the UDP or TCP protocol.
  /// Each entry must be either an integer or a range. For example: `["22"]`,
  /// `["80","443"]`, or `["12345-12349"]`. To match all destination ports,
  /// specify `["0-65535"]`.
  public var destinationPorts: [Swift.String] = []

  /// Output only. The state of the resource.
  public var state: ExternalAccessRule.State = ExternalAccessRule.State()

  /// Output only. System-generated unique identifier for the resource.
  public var uid: Swift.String = Swift.String()

  /// Initialize a new instance of `ExternalAccessRule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExternalAccessRule().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// An IP range provided in any one of the supported formats.
  public struct IpRange: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    public var ipRange: OneOf_IpRange? = nil

    /// Initialize a new instance of `IpRange`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = IpRange().with { $0.ipAddress = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case ipAddress = "ipAddress"
      case ipAddressRange = "ipAddressRange"
      case externalAddress = "externalAddress"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var ipRange: OneOf_IpRange? = nil
      let ipRangeCheckAndSet = {
        if ipRange != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'ipRange'"))
        }
        ipRange = $0
      }
      if let ipAddress = try container.decodeIfPresent(Swift.String.self, forKey: .ipAddress) {
        try ipRangeCheckAndSet(.ipAddress(ipAddress))
      }
      if let ipAddressRange = try container.decodeIfPresent(
        Swift.String.self, forKey: .ipAddressRange)
      {
        try ipRangeCheckAndSet(.ipAddressRange(ipAddressRange))
      }
      if let externalAddress = try container.decodeIfPresent(
        Swift.String.self, forKey: .externalAddress)
      {
        try ipRangeCheckAndSet(.externalAddress(externalAddress))
      }
      self.ipRange = ipRange
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.ipRange {
        switch choice {
        case .ipAddress(let value):
          try container.encode(value, forKey: .ipAddress)
        case .ipAddressRange(let value):
          try container.encode(value, forKey: .ipAddressRange)
        case .externalAddress(let value):
          try container.encode(value, forKey: .externalAddress)
        }
      }
    }

    public enum OneOf_IpRange: Codable, Equatable, Sendable {
      /// A single IP address. For example: `10.0.0.5`.
      case ipAddress(Swift.String)
      /// An IP address range in the CIDR format. For example: `10.0.0.0/24`.
      case ipAddressRange(Swift.String)
      /// The name of an `ExternalAddress` resource. The external address must
      /// have been reserved in the scope of this external access rule's parent
      /// network policy.  Provide the external address name in the form of
      /// `projects/{project}/locations/{location}/privateClouds/{private_cloud}/externalAddresses/{external_address}`.
      /// For example:
      /// `projects/my-project/locations/us-central1-a/privateClouds/my-cloud/externalAddresses/my-address`.
      case externalAddress(Swift.String)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.vmwareengine.v1.ExternalAccessRule.IpRange"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Action determines whether the external access rule permits or blocks
  /// traffic, subject to the other components of the rule matching the traffic.
  public enum Action: Codable, Equatable, Sendable {
    /// Defaults to allow.
    case unspecified
    /// Allows connections that match the other specified components.
    case allow
    /// Blocks connections that match the other specified components.
    case deny
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .allow: return 1
      case .deny: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ACTION_UNSPECIFIED"
      case .allow: return "ALLOW"
      case .deny: return "DENY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Action/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ACTION_UNSPECIFIED": self = .unspecified
      case "ALLOW": self = .allow
      case "DENY": self = .deny
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Action/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .allow
      case 2: self = .deny
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .allow: return try container.encode(1)
      case .deny: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Defines possible states of external access firewall rules.
  public enum State: Codable, Equatable, Sendable {
    /// The default value. This value is used if the state is omitted.
    case unspecified
    /// The rule is ready.
    case active
    /// The rule is being created.
    case creating
    /// The rule is being updated.
    case updating
    /// The rule is being deleted.
    case deleting
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .active: return 1
      case .creating: return 2
      case .updating: return 3
      case .deleting: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .active: return "ACTIVE"
      case .creating: return "CREATING"
      case .updating: return "UPDATING"
      case .deleting: return "DELETING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "ACTIVE": self = .active
      case "CREATING": self = .creating
      case "UPDATING": self = .updating
      case "DELETING": self = .deleting
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .active
      case 2: self = .creating
      case 3: self = .updating
      case 4: self = .deleting
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .active: return try container.encode(1)
      case .creating: return try container.encode(2)
      case .updating: return try container.encode(3)
      case .deleting: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmwareengine.v1.ExternalAccessRule"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
