// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [VmwareEngine.FetchNetworkPolicyExternalAddresses][google.cloud.vmwareengine.v1.VmwareEngine.FetchNetworkPolicyExternalAddresses]
///
/// [google.cloud.vmwareengine.v1.VmwareEngine.FetchNetworkPolicyExternalAddresses]: <doc:VmwareEngineClient/fetchNetworkPolicyExternalAddresses(request:options:)>
public struct FetchNetworkPolicyExternalAddressesRequest: Codable, Equatable, GoogleCloudWkt
    ._AnyPackable,
  Sendable
{
  /// Required. The resource name of the network policy to query for assigned
  /// external IP addresses. Resource names are schemeless URIs that follow the
  /// conventions in https://cloud.google.com/apis/design/resource_names. For
  /// example:
  /// `projects/my-project/locations/us-central1/networkPolicies/my-policy`
  public var networkPolicy: Swift.String = Swift.String()

  /// The maximum number of external IP addresses to return in one page.
  /// The service may return fewer than this value.
  /// The maximum value is coerced to 1000.
  /// The default value of this field is 500.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// A page token, received from a previous
  /// `FetchNetworkPolicyExternalAddresses` call. Provide this to retrieve the
  /// subsequent page.
  ///
  /// When paginating, all parameters provided to
  /// `FetchNetworkPolicyExternalAddresses`, except for `page_size` and
  /// `page_token`, must match the call that provided the page token.
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `FetchNetworkPolicyExternalAddressesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FetchNetworkPolicyExternalAddressesRequest().with { $0.networkPolicy = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.vmwareengine.v1.FetchNetworkPolicyExternalAddressesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
