// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for
/// [VmwareEngine.ListNetworkPolicies][google.cloud.vmwareengine.v1.VmwareEngine.ListNetworkPolicies]
///
/// [google.cloud.vmwareengine.v1.VmwareEngine.ListNetworkPolicies]: <doc:VmwareEngineClient/listNetworkPolicies(request:options:)>
public struct ListNetworkPoliciesRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the location (region) to query for
  /// network policies. Resource names are schemeless URIs that follow the
  /// conventions in https://cloud.google.com/apis/design/resource_names. For
  /// example: `projects/my-project/locations/us-central1`
  public var parent: Swift.String = Swift.String()

  /// The maximum number of network policies to return in one page.
  /// The service may return fewer than this value.
  /// The maximum value is coerced to 1000.
  /// The default value of this field is 500.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// A page token, received from a previous `ListNetworkPolicies` call.
  /// Provide this to retrieve the subsequent page.
  ///
  /// When paginating, all other parameters provided to
  /// `ListNetworkPolicies` must match the call that provided the page
  /// token.
  public var pageToken: Swift.String = Swift.String()

  /// A filter expression that matches resources returned in the response.
  /// The expression must specify the field name, a comparison
  /// operator, and the value that you want to use for filtering. The value
  /// must be a string, a number, or a boolean. The comparison operator
  /// must be `=`, `!=`, `>`, or `<`.
  ///
  /// For example, if you are filtering a list of network policies, you can
  /// exclude the ones named `example-policy` by specifying
  /// `name != "example-policy"`.
  ///
  /// To filter on multiple expressions, provide each separate expression within
  /// parentheses. For example:
  /// ```
  /// (name = "example-policy")
  /// (createTime > "2021-04-12T08:15:10.40Z")
  /// ```
  ///
  /// By default, each expression is an `AND` expression. However, you
  /// can include `AND` and `OR` expressions explicitly.
  /// For example:
  /// ```
  /// (name = "example-policy-1") AND
  /// (createTime > "2021-04-12T08:15:10.40Z") OR
  /// (name = "example-policy-2")
  /// ```
  public var filter: Swift.String = Swift.String()

  /// Sorts list results by a certain order. By default, returned results
  /// are ordered by `name` in ascending order.
  /// You can also sort results in descending order based on the `name` value
  /// using `orderBy="name desc"`.
  /// Currently, only ordering by `name` is supported.
  public var orderBy: Swift.String = Swift.String()

  /// Initialize a new instance of `ListNetworkPoliciesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListNetworkPoliciesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmwareengine.v1.ListNetworkPoliciesRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
