// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for
/// [VmwareEngine.ListPeeringRoutes][google.cloud.vmwareengine.v1.VmwareEngine.ListPeeringRoutes]
///
/// [google.cloud.vmwareengine.v1.VmwareEngine.ListPeeringRoutes]: <doc:VmwareEngineClient/listPeeringRoutes(request:options:)>
public struct ListPeeringRoutesRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the network peering to retrieve peering
  /// routes from. Resource names are schemeless URIs that follow the conventions
  /// in https://cloud.google.com/apis/design/resource_names. For example:
  /// `projects/my-project/locations/global/networkPeerings/my-peering`
  public var parent: Swift.String = Swift.String()

  /// The maximum number of peering routes to return in one page.
  /// The service may return fewer than this value.
  /// The maximum value is coerced to 1000.
  /// The default value of this field is 500.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// A page token, received from a previous `ListPeeringRoutes` call.
  /// Provide this to retrieve the subsequent page.
  /// When paginating, all other parameters provided to `ListPeeringRoutes` must
  /// match the call that provided the page token.
  public var pageToken: Swift.String = Swift.String()

  /// A filter expression that matches resources returned in the response.
  /// Currently, only filtering on the `direction` field is supported. To return
  /// routes imported from the peer network, provide "direction=INCOMING". To
  /// return routes exported from the VMware Engine network, provide
  /// "direction=OUTGOING". Other filter expressions return an error.
  public var filter: Swift.String = Swift.String()

  /// Initialize a new instance of `ListPeeringRoutesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListPeeringRoutesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmwareengine.v1.ListPeeringRoutesRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
