// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [VmwareEngine.ListLoggingServers][google.cloud.vmwareengine.v1.VmwareEngine.ListLoggingServers]
///
/// [google.cloud.vmwareengine.v1.VmwareEngine.ListLoggingServers]: <doc:VmwareEngineClient/listLoggingServers(request:options:)>
public struct ListLoggingServersRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the private cloud to be queried for
  /// logging servers.
  /// Resource names are schemeless URIs that follow the conventions in
  /// https://cloud.google.com/apis/design/resource_names.
  /// For example:
  /// `projects/my-project/locations/us-central1-a/privateClouds/my-cloud`
  public var parent: Swift.String = Swift.String()

  /// The maximum number of logging servers to return in one page.
  /// The service may return fewer than this value.
  /// The maximum value is coerced to 1000.
  /// The default value of this field is 500.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// A page token, received from a previous `ListLoggingServersRequest` call.
  /// Provide this to retrieve the subsequent page.
  ///
  /// When paginating, all other parameters provided to
  /// `ListLoggingServersRequest` must match the call that provided the page
  /// token.
  public var pageToken: Swift.String = Swift.String()

  /// A filter expression that matches resources returned in the response.
  /// The expression must specify the field name, a comparison
  /// operator, and the value that you want to use for filtering. The value
  /// must be a string, a number, or a boolean. The comparison operator
  /// must be `=`, `!=`, `>`, or `<`.
  ///
  /// For example, if you are filtering a list of logging servers, you can
  /// exclude the ones named `example-server` by specifying
  /// `name != "example-server"`.
  ///
  /// To filter on multiple expressions, provide each separate expression within
  /// parentheses. For example:
  /// ```
  /// (name = "example-server")
  /// (createTime > "2021-04-12T08:15:10.40Z")
  /// ```
  ///
  /// By default, each expression is an `AND` expression. However, you
  /// can include `AND` and `OR` expressions explicitly.
  /// For example:
  /// ```
  /// (name = "example-server-1") AND
  /// (createTime > "2021-04-12T08:15:10.40Z") OR
  /// (name = "example-server-2")
  /// ```
  public var filter: Swift.String = Swift.String()

  /// Sorts list results by a certain order. By default, returned results
  /// are ordered by `name` in ascending order.
  /// You can also sort results in descending order based on the `name` value
  /// using `orderBy="name desc"`.
  /// Currently, only ordering by `name` is supported.
  public var orderBy: Swift.String = Swift.String()

  /// Initialize a new instance of `ListLoggingServersRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListLoggingServersRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmwareengine.v1.ListLoggingServersRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
