// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Represents a binding between a network and the management DNS zone.
/// A management DNS zone is the Cloud DNS cross-project binding zone that
/// VMware Engine creates for each private cloud. It contains FQDNs and
/// corresponding IP addresses for the private cloud's ESXi hosts and management
/// VM appliances like vCenter and NSX Manager.
public struct ManagementDnsZoneBinding: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The resource name of this binding.
  /// Resource names are schemeless URIs that follow the conventions in
  /// https://cloud.google.com/apis/design/resource_names.
  /// For example:
  /// `projects/my-project/locations/us-central1-a/privateClouds/my-cloud/managementDnsZoneBindings/my-management-dns-zone-binding`
  public var name: Swift.String = Swift.String()

  /// Output only. Creation time of this resource.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Last update time of this resource.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The state of the resource.
  public var state: ManagementDnsZoneBinding.State = ManagementDnsZoneBinding.State()

  /// User-provided description for this resource.
  public var description: Swift.String = Swift.String()

  /// Output only. System-generated unique identifier for the resource.
  public var uid: Swift.String = Swift.String()

  /// Required. The relative resource name of the network to bind to the
  /// management DNS zone. This network can be a consumer VPC network or a
  /// VMware engine network.
  public var bindNetwork: OneOf_BindNetwork? = nil

  /// Initialize a new instance of `ManagementDnsZoneBinding`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ManagementDnsZoneBinding().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case createTime = "createTime"
    case updateTime = "updateTime"
    case state = "state"
    case description = "description"
    case vpcNetwork = "vpcNetwork"
    case vmwareEngineNetwork = "vmwareEngineNetwork"
    case uid = "uid"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .updateTime)
    self.state = try container.decode(ManagementDnsZoneBinding.State.self, forKey: .state)
    self.description = try container.decode(Swift.String.self, forKey: .description)
    self.uid = try container.decode(Swift.String.self, forKey: .uid)

    var bindNetwork: OneOf_BindNetwork? = nil
    let bindNetworkCheckAndSet = {
      if bindNetwork != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'bindNetwork'"))
      }
      bindNetwork = $0
    }
    if let vpcNetwork = try container.decodeIfPresent(Swift.String.self, forKey: .vpcNetwork) {
      try bindNetworkCheckAndSet(.vpcNetwork(vpcNetwork))
    }
    if let vmwareEngineNetwork = try container.decodeIfPresent(
      Swift.String.self, forKey: .vmwareEngineNetwork)
    {
      try bindNetworkCheckAndSet(.vmwareEngineNetwork(vmwareEngineNetwork))
    }
    self.bindNetwork = bindNetwork
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.updateTime, forKey: .updateTime)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.uid, forKey: .uid)

    if let choice = self.bindNetwork {
      switch choice {
      case .vpcNetwork(let value):
        try container.encode(value, forKey: .vpcNetwork)
      case .vmwareEngineNetwork(let value):
        try container.encode(value, forKey: .vmwareEngineNetwork)
      }
    }
  }

  /// Enum State defines possible states of binding between the consumer VPC
  /// network and the management DNS zone.
  public enum State: Codable, Equatable, Sendable {
    /// The default value. This value should never be used.
    case unspecified
    /// The binding is ready.
    case active
    /// The binding is being created.
    case creating
    /// The binding is being updated.
    case updating
    /// The binding is being deleted.
    case deleting
    /// The binding has failed.
    case failed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .active: return 1
      case .creating: return 2
      case .updating: return 3
      case .deleting: return 4
      case .failed: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .active: return "ACTIVE"
      case .creating: return "CREATING"
      case .updating: return "UPDATING"
      case .deleting: return "DELETING"
      case .failed: return "FAILED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "ACTIVE": self = .active
      case "CREATING": self = .creating
      case "UPDATING": self = .updating
      case "DELETING": self = .deleting
      case "FAILED": self = .failed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .active
      case 2: self = .creating
      case 3: self = .updating
      case 4: self = .deleting
      case 5: self = .failed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .active: return try container.encode(1)
      case .creating: return try container.encode(2)
      case .updating: return try container.encode(3)
      case .deleting: return try container.encode(4)
      case .failed: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Required. The relative resource name of the network to bind to the
  /// management DNS zone. This network can be a consumer VPC network or a
  /// VMware engine network.
  public enum OneOf_BindNetwork: Codable, Equatable, Sendable {
    /// Network to bind is a standard consumer VPC.
    /// Specify the name in the following form for consumer
    /// VPC network: `projects/{project}/global/networks/{network_id}`.
    /// `{project}` can either be a project number or a project ID.
    case vpcNetwork(Swift.String)
    /// Network to bind is a VMware Engine network.
    /// Specify the name in the following form for VMware engine network:
    /// `projects/{project}/locations/global/vmwareEngineNetworks/{vmware_engine_network_id}`.
    /// `{project}` can either be a project number or a project ID.
    case vmwareEngineNetwork(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmwareengine.v1.ManagementDnsZoneBinding"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
