// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Details of a network peering.
public struct NetworkPeering: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The resource name of the network peering. NetworkPeering is a
  /// global resource and location can only be global. Resource names are
  /// scheme-less URIs that follow the conventions in
  /// https://cloud.google.com/apis/design/resource_names.
  /// For example:
  /// `projects/my-project/locations/global/networkPeerings/my-peering`
  public var name: Swift.String = Swift.String()

  /// Output only. Creation time of this resource.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Last update time of this resource.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Required. The relative resource name of the network to peer with
  /// a standard VMware Engine network. The provided network can be a
  /// consumer VPC network or another standard VMware Engine network. If the
  /// `peer_network_type` is VMWARE_ENGINE_NETWORK, specify the name in the form:
  /// `projects/{project}/locations/global/vmwareEngineNetworks/{vmware_engine_network_id}`.
  /// Otherwise specify the name in the form:
  /// `projects/{project}/global/networks/{network_id}`, where
  /// `{project}` can either be a project number or a project ID.
  public var peerNetwork: Swift.String = Swift.String()

  /// Optional. True if custom routes are exported to the peered network;
  /// false otherwise. The default value is true.
  public var exportCustomRoutes: Swift.Bool? = nil

  /// Optional. True if custom routes are imported from the peered network;
  /// false otherwise. The default value is true.
  public var importCustomRoutes: Swift.Bool? = nil

  /// Optional. True if full mesh connectivity is created and managed
  /// automatically between peered networks; false otherwise. Currently this
  /// field is always true because Google Compute Engine automatically creates
  /// and manages subnetwork routes between two VPC networks when peering state
  /// is 'ACTIVE'.
  public var exchangeSubnetRoutes: Swift.Bool? = nil

  /// Optional. True if all subnet routes with a public IP address range are
  /// exported; false otherwise. The default value is true. IPv4 special-use
  /// ranges (https://en.wikipedia.org/wiki/IPv4#Special_addresses) are always
  /// exported to peers and are not controlled by this field.
  public var exportCustomRoutesWithPublicIp: Swift.Bool? = nil

  /// Optional. True if all subnet routes with public IP address range are
  /// imported; false otherwise. The default value is true. IPv4 special-use
  /// ranges (https://en.wikipedia.org/wiki/IPv4#Special_addresses) are always
  /// imported to peers and are not controlled by this field.
  public var importCustomRoutesWithPublicIp: Swift.Bool? = nil

  /// Output only. State of the network peering. This field
  /// has a value of 'ACTIVE' when there's a matching configuration in the peer
  /// network. New values may be added to this enum when appropriate.
  public var state: NetworkPeering.State = NetworkPeering.State()

  /// Output only. Output Only. Details about the current state of the network
  /// peering.
  public var stateDetails: Swift.String = Swift.String()

  /// Optional. Maximum transmission unit (MTU) in bytes.
  /// The default value is `1500`. If a value of `0` is provided for this field,
  /// VMware Engine uses the default value instead.
  public var peerMtu: Swift.Int32 = Swift.Int32()

  /// Required. The type of the network to peer with the VMware Engine network.
  public var peerNetworkType: NetworkPeering.PeerNetworkType = NetworkPeering.PeerNetworkType()

  /// Output only. System-generated unique identifier for the resource.
  public var uid: Swift.String = Swift.String()

  /// Required. The relative resource name of the VMware Engine network.
  /// Specify the name in the following form:
  /// `projects/{project}/locations/{location}/vmwareEngineNetworks/{vmware_engine_network_id}`
  /// where `{project}` can either be a project number or a project ID.
  public var vmwareEngineNetwork: Swift.String = Swift.String()

  /// Optional. User-provided description for this network peering.
  public var description: Swift.String = Swift.String()

  /// Initialize a new instance of `NetworkPeering`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NetworkPeering().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Possible states of a network peering.
  public enum State: Codable, Equatable, Sendable {
    /// Unspecified network peering state. This is the default value.
    case unspecified
    /// The peering is not active.
    case inactive
    /// The peering is active.
    case active
    /// The peering is being created.
    case creating
    /// The peering is being deleted.
    case deleting
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .inactive: return 1
      case .active: return 2
      case .creating: return 3
      case .deleting: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .inactive: return "INACTIVE"
      case .active: return "ACTIVE"
      case .creating: return "CREATING"
      case .deleting: return "DELETING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "INACTIVE": self = .inactive
      case "ACTIVE": self = .active
      case "CREATING": self = .creating
      case "DELETING": self = .deleting
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .inactive
      case 2: self = .active
      case 3: self = .creating
      case 4: self = .deleting
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .inactive: return try container.encode(1)
      case .active: return try container.encode(2)
      case .creating: return try container.encode(3)
      case .deleting: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Type or purpose of the network peering connection.
  public enum PeerNetworkType: Codable, Equatable, Sendable {
    /// Unspecified
    case unspecified
    /// Peering connection used for connecting to another VPC network established
    /// by the same user. For example, a peering connection to another VPC
    /// network in the same project or to an on-premises network.
    case standard
    /// Peering connection used for connecting to another VMware Engine network.
    case vmwareEngineNetwork
    /// Peering connection used for establishing [private services
    /// access](https://cloud.google.com/vpc/docs/private-services-access).
    case privateServicesAccess
    /// Peering connection used for connecting to NetApp Cloud Volumes.
    case netappCloudVolumes
    /// Peering connection used for connecting to third-party services. Most
    /// third-party services require manual setup of reverse peering on the VPC
    /// network associated with the third-party service.
    case thirdPartyService
    /// Peering connection used for connecting to Dell PowerScale Filers
    case dellPowerscale
    /// Peering connection used for connecting to Google Cloud NetApp Volumes.
    case googleCloudNetappVolumes
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .standard: return 1
      case .vmwareEngineNetwork: return 2
      case .privateServicesAccess: return 3
      case .netappCloudVolumes: return 4
      case .thirdPartyService: return 5
      case .dellPowerscale: return 6
      case .googleCloudNetappVolumes: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PEER_NETWORK_TYPE_UNSPECIFIED"
      case .standard: return "STANDARD"
      case .vmwareEngineNetwork: return "VMWARE_ENGINE_NETWORK"
      case .privateServicesAccess: return "PRIVATE_SERVICES_ACCESS"
      case .netappCloudVolumes: return "NETAPP_CLOUD_VOLUMES"
      case .thirdPartyService: return "THIRD_PARTY_SERVICE"
      case .dellPowerscale: return "DELL_POWERSCALE"
      case .googleCloudNetappVolumes: return "GOOGLE_CLOUD_NETAPP_VOLUMES"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:PeerNetworkType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PEER_NETWORK_TYPE_UNSPECIFIED": self = .unspecified
      case "STANDARD": self = .standard
      case "VMWARE_ENGINE_NETWORK": self = .vmwareEngineNetwork
      case "PRIVATE_SERVICES_ACCESS": self = .privateServicesAccess
      case "NETAPP_CLOUD_VOLUMES": self = .netappCloudVolumes
      case "THIRD_PARTY_SERVICE": self = .thirdPartyService
      case "DELL_POWERSCALE": self = .dellPowerscale
      case "GOOGLE_CLOUD_NETAPP_VOLUMES": self = .googleCloudNetappVolumes
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:PeerNetworkType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .standard
      case 2: self = .vmwareEngineNetwork
      case 3: self = .privateServicesAccess
      case 4: self = .netappCloudVolumes
      case 5: self = .thirdPartyService
      case 6: self = .dellPowerscale
      case 7: self = .googleCloudNetappVolumes
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .standard: return try container.encode(1)
      case .vmwareEngineNetwork: return try container.encode(2)
      case .privateServicesAccess: return try container.encode(3)
      case .netappCloudVolumes: return try container.encode(4)
      case .thirdPartyService: return try container.encode(5)
      case .dellPowerscale: return try container.encode(6)
      case .googleCloudNetappVolumes: return try container.encode(7)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmwareengine.v1.NetworkPeering"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
