// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Network configuration in the consumer project
/// with which the peering has to be done.
public struct NetworkConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Management CIDR used by VMware management appliances.
  public var managementCidr: Swift.String = Swift.String()

  /// Optional. The relative resource name of the VMware Engine network attached
  /// to the private cloud. Specify the name in the following form:
  /// `projects/{project}/locations/{location}/vmwareEngineNetworks/{vmware_engine_network_id}`
  /// where `{project}` can either be a project number or a project ID.
  public var vmwareEngineNetwork: Swift.String = Swift.String()

  /// Output only. The canonical name of the VMware Engine network in the form:
  /// `projects/{project_number}/locations/{location}/vmwareEngineNetworks/{vmware_engine_network_id}`
  public var vmwareEngineNetworkCanonical: Swift.String = Swift.String()

  /// Output only. The IP address layout version of the management IP address
  /// range. Possible versions include:
  /// * `managementIpAddressLayoutVersion=1`: Indicates the legacy IP address
  /// layout used by some existing private clouds. This is no longer supported
  /// for new private clouds as it does not support all features.
  /// * `managementIpAddressLayoutVersion=2`: Indicates the latest IP address
  /// layout used by all newly created private clouds. This version supports all
  /// current features.
  public var managementIpAddressLayoutVersion: Swift.Int32 = Swift.Int32()

  /// Output only. DNS Server IP of the Private Cloud.
  /// All DNS queries can be forwarded to this address for name resolution of
  /// Private Cloud's management entities like vCenter, NSX-T Manager and
  /// ESXi hosts.
  public var dnsServerIp: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `NetworkConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NetworkConfig().with { $0.managementCidr = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let managementCidr = CodingKeys(stringValue: "managementCidr")
    static let vmwareEngineNetwork = CodingKeys(stringValue: "vmwareEngineNetwork")
    static let vmwareEngineNetworkCanonical = CodingKeys(
      stringValue: "vmwareEngineNetworkCanonical")
    static let managementIpAddressLayoutVersion = CodingKeys(
      stringValue: "managementIpAddressLayoutVersion")
    static let dnsServerIp = CodingKeys(stringValue: "dnsServerIp")

    static let _knownKeys: Set<Swift.String> = [
      "managementCidr",
      "vmwareEngineNetwork",
      "vmwareEngineNetworkCanonical",
      "managementIpAddressLayoutVersion",
      "dnsServerIp",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .managementCidr) {
      self.managementCidr = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .vmwareEngineNetwork) {
      self.vmwareEngineNetwork = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .vmwareEngineNetworkCanonical)
    {
      self.vmwareEngineNetworkCanonical = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Int32.self, forKey: .managementIpAddressLayoutVersion)
    {
      self.managementIpAddressLayoutVersion = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .dnsServerIp) {
      self.dnsServerIp = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.managementCidr, forKey: .managementCidr)
    try container.encode(self.vmwareEngineNetwork, forKey: .vmwareEngineNetwork)
    try container.encode(self.vmwareEngineNetworkCanonical, forKey: .vmwareEngineNetworkCanonical)
    try container.encode(
      self.managementIpAddressLayoutVersion, forKey: .managementIpAddressLayoutVersion)
    try container.encode(self.dnsServerIp, forKey: .dnsServerIp)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmwareengine.v1.NetworkConfig"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
