// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Represents a private cloud resource. Private clouds of type `STANDARD` and
/// `TIME_LIMITED` are zonal resources, `STRETCHED` private clouds are
/// regional.
public struct PrivateCloud: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The resource name of this private cloud.
  /// Resource names are schemeless URIs that follow the conventions in
  /// https://cloud.google.com/apis/design/resource_names.
  /// For example:
  /// `projects/my-project/locations/us-central1-a/privateClouds/my-cloud`
  public var name: Swift.String = Swift.String()

  /// Output only. Creation time of this resource.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Last update time of this resource.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Time when the resource was scheduled for deletion.
  public var deleteTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Time when the resource will be irreversibly deleted.
  public var expireTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. State of the resource. New values may be added to this enum
  /// when appropriate.
  public var state: PrivateCloud.State = PrivateCloud.State()

  /// Required. Network configuration of the private cloud.
  public var networkConfig: NetworkConfig? = nil

  /// Required. Input only. The management cluster for this private cloud.
  /// This field is required during creation of the private cloud to provide
  /// details for the default cluster.
  ///
  /// The following fields can't be changed after private cloud creation:
  /// `ManagementCluster.clusterId`, `ManagementCluster.nodeTypeId`.
  public var managementCluster: PrivateCloud.ManagementCluster? = nil

  /// User-provided description for this private cloud.
  public var description: Swift.String = Swift.String()

  /// Output only. HCX appliance.
  public var hcx: Hcx? = nil

  /// Output only. NSX appliance.
  public var nsx: Nsx? = nil

  /// Output only. Vcenter appliance.
  public var vcenter: Vcenter? = nil

  /// Output only. System-generated unique identifier for the resource.
  public var uid: Swift.String = Swift.String()

  /// Optional. Type of the private cloud. Defaults to STANDARD.
  public var type: PrivateCloud.Type_ = PrivateCloud.Type_()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `PrivateCloud`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PrivateCloud().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let deleteTime = CodingKeys(stringValue: "deleteTime")
    static let expireTime = CodingKeys(stringValue: "expireTime")
    static let state = CodingKeys(stringValue: "state")
    static let networkConfig = CodingKeys(stringValue: "networkConfig")
    static let managementCluster = CodingKeys(stringValue: "managementCluster")
    static let description = CodingKeys(stringValue: "description")
    static let hcx = CodingKeys(stringValue: "hcx")
    static let nsx = CodingKeys(stringValue: "nsx")
    static let vcenter = CodingKeys(stringValue: "vcenter")
    static let uid = CodingKeys(stringValue: "uid")
    static let type = CodingKeys(stringValue: "type")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "updateTime",
      "deleteTime",
      "expireTime",
      "state",
      "networkConfig",
      "managementCluster",
      "description",
      "hcx",
      "nsx",
      "vcenter",
      "uid",
      "type",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    self.deleteTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .deleteTime)
    self.expireTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .expireTime)
    if let value = try container.decodeIfPresent(PrivateCloud.State.self, forKey: .state) {
      self.state = value
    }
    self.networkConfig = try container.decodeIfPresent(NetworkConfig.self, forKey: .networkConfig)
    self.managementCluster = try container.decodeIfPresent(
      PrivateCloud.ManagementCluster.self, forKey: .managementCluster)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    self.hcx = try container.decodeIfPresent(Hcx.self, forKey: .hcx)
    self.nsx = try container.decodeIfPresent(Nsx.self, forKey: .nsx)
    self.vcenter = try container.decodeIfPresent(Vcenter.self, forKey: .vcenter)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      self.uid = value
    }
    if let value = try container.decodeIfPresent(PrivateCloud.Type_.self, forKey: .type) {
      self.type = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.deleteTime, forKey: .deleteTime)
    try container.encodeIfPresent(self.expireTime, forKey: .expireTime)
    try container.encode(self.state, forKey: .state)
    try container.encodeIfPresent(self.networkConfig, forKey: .networkConfig)
    try container.encodeIfPresent(self.managementCluster, forKey: .managementCluster)
    try container.encode(self.description, forKey: .description)
    try container.encodeIfPresent(self.hcx, forKey: .hcx)
    try container.encodeIfPresent(self.nsx, forKey: .nsx)
    try container.encodeIfPresent(self.vcenter, forKey: .vcenter)
    try container.encode(self.uid, forKey: .uid)
    try container.encode(self.type, forKey: .type)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Management cluster configuration.
  public struct ManagementCluster: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The user-provided identifier of the new `Cluster`.
    /// The identifier must meet the following requirements:
    ///
    /// * Only contains 1-63 alphanumeric characters and hyphens
    /// * Begins with an alphabetical character
    /// * Ends with a non-hyphen character
    /// * Not formatted as a UUID
    /// * Complies with [RFC
    /// 1034](https://datatracker.ietf.org/doc/html/rfc1034) (section 3.5)
    public var clusterId: Swift.String = Swift.String()

    /// Required. The map of cluster node types in this cluster, where the key is
    /// canonical identifier of the node type (corresponds to the `NodeType`).
    public var nodeTypeConfigs: [Swift.String: NodeTypeConfig] = [:]

    /// Optional. Configuration of a stretched cluster. Required for STRETCHED
    /// private clouds.
    public var stretchedClusterConfig: StretchedClusterConfig? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ManagementCluster`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ManagementCluster().with { $0.clusterId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let clusterId = CodingKeys(stringValue: "clusterId")
      static let nodeTypeConfigs = CodingKeys(stringValue: "nodeTypeConfigs")
      static let stretchedClusterConfig = CodingKeys(stringValue: "stretchedClusterConfig")

      static let _knownKeys: Set<Swift.String> = [
        "clusterId",
        "nodeTypeConfigs",
        "stretchedClusterConfig",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .clusterId) {
        self.clusterId = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String: NodeTypeConfig].self, forKey: .nodeTypeConfigs)
      {
        self.nodeTypeConfigs = value
      }
      self.stretchedClusterConfig = try container.decodeIfPresent(
        StretchedClusterConfig.self, forKey: .stretchedClusterConfig)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.clusterId, forKey: .clusterId)
      try container.encode(self.nodeTypeConfigs, forKey: .nodeTypeConfigs)
      try container.encodeIfPresent(self.stretchedClusterConfig, forKey: .stretchedClusterConfig)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.vmwareengine.v1.PrivateCloud.ManagementCluster"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Enum State defines possible states of private clouds.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Hashable, Sendable {
    /// The default value. This value should never be used.
    case unspecified
    /// The private cloud is ready.
    case active
    /// The private cloud is being created.
    case creating
    /// The private cloud is being updated.
    case updating
    /// The private cloud is in failed state.
    case failed
    /// The private cloud is scheduled for deletion. The deletion process can be
    /// cancelled by using the corresponding undelete method.
    case deleted
    /// The private cloud is irreversibly deleted and is being removed from the
    /// system.
    case purging
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .active: return 1
      case .creating: return 2
      case .updating: return 3
      case .failed: return 5
      case .deleted: return 6
      case .purging: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .active: return "ACTIVE"
      case .creating: return "CREATING"
      case .updating: return "UPDATING"
      case .failed: return "FAILED"
      case .deleted: return "DELETED"
      case .purging: return "PURGING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "ACTIVE": self = .active
      case "CREATING": self = .creating
      case "UPDATING": self = .updating
      case "FAILED": self = .failed
      case "DELETED": self = .deleted
      case "PURGING": self = .purging
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .active
      case 2: self = .creating
      case 3: self = .updating
      case 5: self = .failed
      case 6: self = .deleted
      case 7: self = .purging
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .active: return try container.encode("ACTIVE")
      case .creating: return try container.encode("CREATING")
      case .updating: return try container.encode("UPDATING")
      case .failed: return try container.encode("FAILED")
      case .deleted: return try container.encode("DELETED")
      case .purging: return try container.encode("PURGING")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Enum Type defines private cloud type.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Type_: Codable, Equatable, Hashable, Sendable {
    /// Standard private is a zonal resource, with 3+ nodes. Default type.
    case standard
    /// Time limited private cloud is a zonal resource, can have only 1 node and
    /// has limited life span. Will be deleted after defined period of time,
    /// can be converted into standard private cloud by expanding it up to 3
    /// or more nodes.
    case timeLimited
    /// Stretched private cloud is a regional resource with redundancy,
    /// with a minimum of 6 nodes, nodes count has to be even.
    case stretched
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .standard
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .standard: return 0
      case .timeLimited: return 1
      case .stretched: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .standard: return "STANDARD"
      case .timeLimited: return "TIME_LIMITED"
      case .stretched: return "STRETCHED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Type_/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STANDARD": self = .standard
      case "TIME_LIMITED": self = .timeLimited
      case "STRETCHED": self = .stretched
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Type_/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .standard
      case 1: self = .timeLimited
      case 2: self = .stretched
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .standard: return try container.encode("STANDARD")
      case .timeLimited: return try container.encode("TIME_LIMITED")
      case .stretched: return try container.encode("STRETCHED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmwareengine.v1.PrivateCloud"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
