// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Configuration of a stretched cluster.
public struct StretchedClusterConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Zone that will remain operational when connection between the two
  /// zones is lost. Specify the resource name of a zone that belongs to the
  /// region of the private cloud. For example:
  /// `projects/{project}/locations/europe-west3-a` where `{project}` can either
  /// be a project number or a project ID.
  public var preferredLocation: Swift.String = Swift.String()

  /// Required. Additional zone for a higher level of availability and load
  /// balancing. Specify the resource name of a zone that belongs to the region
  /// of the private cloud. For example:
  /// `projects/{project}/locations/europe-west3-b` where `{project}` can either
  /// be a project number or a project ID.
  public var secondaryLocation: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `StretchedClusterConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StretchedClusterConfig().with { $0.preferredLocation = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let preferredLocation = CodingKeys(stringValue: "preferredLocation")
    static let secondaryLocation = CodingKeys(stringValue: "secondaryLocation")

    static let _knownKeys: Set<Swift.String> = [
      "preferredLocation",
      "secondaryLocation",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .preferredLocation) {
      self.preferredLocation = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .secondaryLocation) {
      self.secondaryLocation = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.preferredLocation, forKey: .preferredLocation)
    try container.encode(self.secondaryLocation, forKey: .secondaryLocation)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmwareengine.v1.StretchedClusterConfig"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
