// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Configuration of a stretched cluster.
public struct StretchedClusterConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Zone that will remain operational when connection between the two
  /// zones is lost. Specify the resource name of a zone that belongs to the
  /// region of the private cloud. For example:
  /// `projects/{project}/locations/europe-west3-a` where `{project}` can either
  /// be a project number or a project ID.
  public var preferredLocation: Swift.String = Swift.String()

  /// Required. Additional zone for a higher level of availability and load
  /// balancing. Specify the resource name of a zone that belongs to the region
  /// of the private cloud. For example:
  /// `projects/{project}/locations/europe-west3-b` where `{project}` can either
  /// be a project number or a project ID.
  public var secondaryLocation: Swift.String = Swift.String()

  /// Initialize a new instance of `StretchedClusterConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StretchedClusterConfig().with { $0.preferredLocation = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmwareengine.v1.StretchedClusterConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
