// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class VmwareEngineLogging: VmwareEngineStub {
    let inner: any VmwareEngineStub
    let logger: Logger

    public init(_ inner: any VmwareEngineStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-vmwareengine-v1"
      logger[metadataKey: "gcp.client.service"] = "vmwareengine"
      logger[metadataKey: "gcp.experimental.swift.client"] = "VmwareEngine"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listPrivateClouds(
      request: ListPrivateCloudsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ListPrivateCloudsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listPrivateClouds",
        action: {
          (r: ListPrivateCloudsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMwareEngineV1.ListPrivateCloudsResponse
          in
          return try await self.inner.listPrivateClouds(request: r, options: o)
        })
    }

    public func getPrivateCloud(
      request: GetPrivateCloudRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.PrivateCloud {
      try await self._intercept(
        request: request,
        options: options,
        name: "getPrivateCloud",
        action: {
          (r: GetPrivateCloudRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMwareEngineV1.PrivateCloud
          in
          return try await self.inner.getPrivateCloud(request: r, options: o)
        })
    }

    public func createPrivateCloud(
      request: CreatePrivateCloudRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createPrivateCloud",
        action: {
          (r: CreatePrivateCloudRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createPrivateCloud(request: r, options: o)
        })
    }

    public func updatePrivateCloud(
      request: UpdatePrivateCloudRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updatePrivateCloud",
        action: {
          (r: UpdatePrivateCloudRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updatePrivateCloud(request: r, options: o)
        })
    }

    public func deletePrivateCloud(
      request: DeletePrivateCloudRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deletePrivateCloud",
        action: {
          (r: DeletePrivateCloudRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deletePrivateCloud(request: r, options: o)
        })
    }

    public func undeletePrivateCloud(
      request: UndeletePrivateCloudRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "undeletePrivateCloud",
        action: {
          (r: UndeletePrivateCloudRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.undeletePrivateCloud(request: r, options: o)
        })
    }

    public func listClusters(
      request: ListClustersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ListClustersResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listClusters",
        action: {
          (r: ListClustersRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMwareEngineV1.ListClustersResponse
          in
          return try await self.inner.listClusters(request: r, options: o)
        })
    }

    public func getCluster(
      request: GetClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.Cluster {
      try await self._intercept(
        request: request,
        options: options,
        name: "getCluster",
        action: {
          (r: GetClusterRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMwareEngineV1.Cluster
          in
          return try await self.inner.getCluster(request: r, options: o)
        })
    }

    public func createCluster(
      request: CreateClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createCluster",
        action: {
          (r: CreateClusterRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createCluster(request: r, options: o)
        })
    }

    public func updateCluster(
      request: UpdateClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateCluster",
        action: {
          (r: UpdateClusterRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateCluster(request: r, options: o)
        })
    }

    public func deleteCluster(
      request: DeleteClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteCluster",
        action: {
          (r: DeleteClusterRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteCluster(request: r, options: o)
        })
    }

    public func listNodes(
      request: ListNodesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ListNodesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listNodes",
        action: {
          (r: ListNodesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMwareEngineV1.ListNodesResponse
          in
          return try await self.inner.listNodes(request: r, options: o)
        })
    }

    public func getNode(
      request: GetNodeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.Node {
      try await self._intercept(
        request: request,
        options: options,
        name: "getNode",
        action: {
          (r: GetNodeRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMwareEngineV1.Node
          in
          return try await self.inner.getNode(request: r, options: o)
        })
    }

    public func listExternalAddresses(
      request: ListExternalAddressesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ListExternalAddressesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listExternalAddresses",
        action: {
          (r: ListExternalAddressesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMwareEngineV1.ListExternalAddressesResponse
          in
          return try await self.inner.listExternalAddresses(request: r, options: o)
        })
    }

    public func fetchNetworkPolicyExternalAddresses(
      request: FetchNetworkPolicyExternalAddressesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.FetchNetworkPolicyExternalAddressesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "fetchNetworkPolicyExternalAddresses",
        action: {
          (r: FetchNetworkPolicyExternalAddressesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMwareEngineV1.FetchNetworkPolicyExternalAddressesResponse
          in
          return try await self.inner.fetchNetworkPolicyExternalAddresses(request: r, options: o)
        })
    }

    public func getExternalAddress(
      request: GetExternalAddressRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ExternalAddress {
      try await self._intercept(
        request: request,
        options: options,
        name: "getExternalAddress",
        action: {
          (r: GetExternalAddressRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMwareEngineV1.ExternalAddress
          in
          return try await self.inner.getExternalAddress(request: r, options: o)
        })
    }

    public func createExternalAddress(
      request: CreateExternalAddressRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createExternalAddress",
        action: {
          (r: CreateExternalAddressRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createExternalAddress(request: r, options: o)
        })
    }

    public func updateExternalAddress(
      request: UpdateExternalAddressRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateExternalAddress",
        action: {
          (r: UpdateExternalAddressRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateExternalAddress(request: r, options: o)
        })
    }

    public func deleteExternalAddress(
      request: DeleteExternalAddressRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteExternalAddress",
        action: {
          (r: DeleteExternalAddressRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteExternalAddress(request: r, options: o)
        })
    }

    public func listSubnets(
      request: ListSubnetsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ListSubnetsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listSubnets",
        action: {
          (r: ListSubnetsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMwareEngineV1.ListSubnetsResponse
          in
          return try await self.inner.listSubnets(request: r, options: o)
        })
    }

    public func getSubnet(
      request: GetSubnetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.Subnet {
      try await self._intercept(
        request: request,
        options: options,
        name: "getSubnet",
        action: {
          (r: GetSubnetRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMwareEngineV1.Subnet
          in
          return try await self.inner.getSubnet(request: r, options: o)
        })
    }

    public func updateSubnet(
      request: UpdateSubnetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateSubnet",
        action: {
          (r: UpdateSubnetRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateSubnet(request: r, options: o)
        })
    }

    public func listExternalAccessRules(
      request: ListExternalAccessRulesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ListExternalAccessRulesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listExternalAccessRules",
        action: {
          (r: ListExternalAccessRulesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMwareEngineV1.ListExternalAccessRulesResponse
          in
          return try await self.inner.listExternalAccessRules(request: r, options: o)
        })
    }

    public func getExternalAccessRule(
      request: GetExternalAccessRuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ExternalAccessRule {
      try await self._intercept(
        request: request,
        options: options,
        name: "getExternalAccessRule",
        action: {
          (r: GetExternalAccessRuleRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMwareEngineV1.ExternalAccessRule
          in
          return try await self.inner.getExternalAccessRule(request: r, options: o)
        })
    }

    public func createExternalAccessRule(
      request: CreateExternalAccessRuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createExternalAccessRule",
        action: {
          (r: CreateExternalAccessRuleRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createExternalAccessRule(request: r, options: o)
        })
    }

    public func updateExternalAccessRule(
      request: UpdateExternalAccessRuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateExternalAccessRule",
        action: {
          (r: UpdateExternalAccessRuleRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateExternalAccessRule(request: r, options: o)
        })
    }

    public func deleteExternalAccessRule(
      request: DeleteExternalAccessRuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteExternalAccessRule",
        action: {
          (r: DeleteExternalAccessRuleRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteExternalAccessRule(request: r, options: o)
        })
    }

    public func listLoggingServers(
      request: ListLoggingServersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ListLoggingServersResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLoggingServers",
        action: {
          (r: ListLoggingServersRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMwareEngineV1.ListLoggingServersResponse
          in
          return try await self.inner.listLoggingServers(request: r, options: o)
        })
    }

    public func getLoggingServer(
      request: GetLoggingServerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.LoggingServer {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLoggingServer",
        action: {
          (r: GetLoggingServerRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMwareEngineV1.LoggingServer
          in
          return try await self.inner.getLoggingServer(request: r, options: o)
        })
    }

    public func createLoggingServer(
      request: CreateLoggingServerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createLoggingServer",
        action: {
          (r: CreateLoggingServerRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createLoggingServer(request: r, options: o)
        })
    }

    public func updateLoggingServer(
      request: UpdateLoggingServerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateLoggingServer",
        action: {
          (r: UpdateLoggingServerRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateLoggingServer(request: r, options: o)
        })
    }

    public func deleteLoggingServer(
      request: DeleteLoggingServerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteLoggingServer",
        action: {
          (r: DeleteLoggingServerRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteLoggingServer(request: r, options: o)
        })
    }

    public func listNodeTypes(
      request: ListNodeTypesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ListNodeTypesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listNodeTypes",
        action: {
          (r: ListNodeTypesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMwareEngineV1.ListNodeTypesResponse
          in
          return try await self.inner.listNodeTypes(request: r, options: o)
        })
    }

    public func getNodeType(
      request: GetNodeTypeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.NodeType {
      try await self._intercept(
        request: request,
        options: options,
        name: "getNodeType",
        action: {
          (r: GetNodeTypeRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMwareEngineV1.NodeType
          in
          return try await self.inner.getNodeType(request: r, options: o)
        })
    }

    public func showNsxCredentials(
      request: ShowNsxCredentialsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.Credentials {
      try await self._intercept(
        request: request,
        options: options,
        name: "showNsxCredentials",
        action: {
          (r: ShowNsxCredentialsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMwareEngineV1.Credentials
          in
          return try await self.inner.showNsxCredentials(request: r, options: o)
        })
    }

    public func showVcenterCredentials(
      request: ShowVcenterCredentialsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.Credentials {
      try await self._intercept(
        request: request,
        options: options,
        name: "showVcenterCredentials",
        action: {
          (r: ShowVcenterCredentialsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMwareEngineV1.Credentials
          in
          return try await self.inner.showVcenterCredentials(request: r, options: o)
        })
    }

    public func resetNsxCredentials(
      request: ResetNsxCredentialsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "resetNsxCredentials",
        action: {
          (r: ResetNsxCredentialsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.resetNsxCredentials(request: r, options: o)
        })
    }

    public func resetVcenterCredentials(
      request: ResetVcenterCredentialsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "resetVcenterCredentials",
        action: {
          (r: ResetVcenterCredentialsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.resetVcenterCredentials(request: r, options: o)
        })
    }

    public func getDnsForwarding(
      request: GetDnsForwardingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.DnsForwarding {
      try await self._intercept(
        request: request,
        options: options,
        name: "getDnsForwarding",
        action: {
          (r: GetDnsForwardingRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMwareEngineV1.DnsForwarding
          in
          return try await self.inner.getDnsForwarding(request: r, options: o)
        })
    }

    public func updateDnsForwarding(
      request: UpdateDnsForwardingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateDnsForwarding",
        action: {
          (r: UpdateDnsForwardingRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateDnsForwarding(request: r, options: o)
        })
    }

    public func getNetworkPeering(
      request: GetNetworkPeeringRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.NetworkPeering {
      try await self._intercept(
        request: request,
        options: options,
        name: "getNetworkPeering",
        action: {
          (r: GetNetworkPeeringRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMwareEngineV1.NetworkPeering
          in
          return try await self.inner.getNetworkPeering(request: r, options: o)
        })
    }

    public func listNetworkPeerings(
      request: ListNetworkPeeringsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ListNetworkPeeringsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listNetworkPeerings",
        action: {
          (r: ListNetworkPeeringsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMwareEngineV1.ListNetworkPeeringsResponse
          in
          return try await self.inner.listNetworkPeerings(request: r, options: o)
        })
    }

    public func createNetworkPeering(
      request: CreateNetworkPeeringRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createNetworkPeering",
        action: {
          (r: CreateNetworkPeeringRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createNetworkPeering(request: r, options: o)
        })
    }

    public func deleteNetworkPeering(
      request: DeleteNetworkPeeringRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteNetworkPeering",
        action: {
          (r: DeleteNetworkPeeringRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteNetworkPeering(request: r, options: o)
        })
    }

    public func updateNetworkPeering(
      request: UpdateNetworkPeeringRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateNetworkPeering",
        action: {
          (r: UpdateNetworkPeeringRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateNetworkPeering(request: r, options: o)
        })
    }

    public func listPeeringRoutes(
      request: ListPeeringRoutesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ListPeeringRoutesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listPeeringRoutes",
        action: {
          (r: ListPeeringRoutesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMwareEngineV1.ListPeeringRoutesResponse
          in
          return try await self.inner.listPeeringRoutes(request: r, options: o)
        })
    }

    public func createHcxActivationKey(
      request: CreateHcxActivationKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createHcxActivationKey",
        action: {
          (r: CreateHcxActivationKeyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createHcxActivationKey(request: r, options: o)
        })
    }

    public func listHcxActivationKeys(
      request: ListHcxActivationKeysRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ListHcxActivationKeysResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listHcxActivationKeys",
        action: {
          (r: ListHcxActivationKeysRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMwareEngineV1.ListHcxActivationKeysResponse
          in
          return try await self.inner.listHcxActivationKeys(request: r, options: o)
        })
    }

    public func getHcxActivationKey(
      request: GetHcxActivationKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.HcxActivationKey {
      try await self._intercept(
        request: request,
        options: options,
        name: "getHcxActivationKey",
        action: {
          (r: GetHcxActivationKeyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMwareEngineV1.HcxActivationKey
          in
          return try await self.inner.getHcxActivationKey(request: r, options: o)
        })
    }

    public func getNetworkPolicy(
      request: GetNetworkPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.NetworkPolicy {
      try await self._intercept(
        request: request,
        options: options,
        name: "getNetworkPolicy",
        action: {
          (r: GetNetworkPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMwareEngineV1.NetworkPolicy
          in
          return try await self.inner.getNetworkPolicy(request: r, options: o)
        })
    }

    public func listNetworkPolicies(
      request: ListNetworkPoliciesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ListNetworkPoliciesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listNetworkPolicies",
        action: {
          (r: ListNetworkPoliciesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMwareEngineV1.ListNetworkPoliciesResponse
          in
          return try await self.inner.listNetworkPolicies(request: r, options: o)
        })
    }

    public func createNetworkPolicy(
      request: CreateNetworkPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createNetworkPolicy",
        action: {
          (r: CreateNetworkPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createNetworkPolicy(request: r, options: o)
        })
    }

    public func updateNetworkPolicy(
      request: UpdateNetworkPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateNetworkPolicy",
        action: {
          (r: UpdateNetworkPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateNetworkPolicy(request: r, options: o)
        })
    }

    public func deleteNetworkPolicy(
      request: DeleteNetworkPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteNetworkPolicy",
        action: {
          (r: DeleteNetworkPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteNetworkPolicy(request: r, options: o)
        })
    }

    public func listManagementDnsZoneBindings(
      request: ListManagementDnsZoneBindingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ListManagementDnsZoneBindingsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listManagementDnsZoneBindings",
        action: {
          (r: ListManagementDnsZoneBindingsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMwareEngineV1.ListManagementDnsZoneBindingsResponse
          in
          return try await self.inner.listManagementDnsZoneBindings(request: r, options: o)
        })
    }

    public func getManagementDnsZoneBinding(
      request: GetManagementDnsZoneBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ManagementDnsZoneBinding {
      try await self._intercept(
        request: request,
        options: options,
        name: "getManagementDnsZoneBinding",
        action: {
          (r: GetManagementDnsZoneBindingRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMwareEngineV1.ManagementDnsZoneBinding
          in
          return try await self.inner.getManagementDnsZoneBinding(request: r, options: o)
        })
    }

    public func createManagementDnsZoneBinding(
      request: CreateManagementDnsZoneBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createManagementDnsZoneBinding",
        action: {
          (r: CreateManagementDnsZoneBindingRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createManagementDnsZoneBinding(request: r, options: o)
        })
    }

    public func updateManagementDnsZoneBinding(
      request: UpdateManagementDnsZoneBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateManagementDnsZoneBinding",
        action: {
          (r: UpdateManagementDnsZoneBindingRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateManagementDnsZoneBinding(request: r, options: o)
        })
    }

    public func deleteManagementDnsZoneBinding(
      request: DeleteManagementDnsZoneBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteManagementDnsZoneBinding",
        action: {
          (r: DeleteManagementDnsZoneBindingRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteManagementDnsZoneBinding(request: r, options: o)
        })
    }

    public func repairManagementDnsZoneBinding(
      request: RepairManagementDnsZoneBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "repairManagementDnsZoneBinding",
        action: {
          (r: RepairManagementDnsZoneBindingRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.repairManagementDnsZoneBinding(request: r, options: o)
        })
    }

    public func createVmwareEngineNetwork(
      request: CreateVmwareEngineNetworkRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createVmwareEngineNetwork",
        action: {
          (r: CreateVmwareEngineNetworkRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createVmwareEngineNetwork(request: r, options: o)
        })
    }

    public func updateVmwareEngineNetwork(
      request: UpdateVmwareEngineNetworkRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateVmwareEngineNetwork",
        action: {
          (r: UpdateVmwareEngineNetworkRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateVmwareEngineNetwork(request: r, options: o)
        })
    }

    public func deleteVmwareEngineNetwork(
      request: DeleteVmwareEngineNetworkRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteVmwareEngineNetwork",
        action: {
          (r: DeleteVmwareEngineNetworkRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteVmwareEngineNetwork(request: r, options: o)
        })
    }

    public func getVmwareEngineNetwork(
      request: GetVmwareEngineNetworkRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.VmwareEngineNetwork {
      try await self._intercept(
        request: request,
        options: options,
        name: "getVmwareEngineNetwork",
        action: {
          (r: GetVmwareEngineNetworkRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMwareEngineV1.VmwareEngineNetwork
          in
          return try await self.inner.getVmwareEngineNetwork(request: r, options: o)
        })
    }

    public func listVmwareEngineNetworks(
      request: ListVmwareEngineNetworksRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ListVmwareEngineNetworksResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listVmwareEngineNetworks",
        action: {
          (r: ListVmwareEngineNetworksRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMwareEngineV1.ListVmwareEngineNetworksResponse
          in
          return try await self.inner.listVmwareEngineNetworks(request: r, options: o)
        })
    }

    public func createPrivateConnection(
      request: CreatePrivateConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createPrivateConnection",
        action: {
          (r: CreatePrivateConnectionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createPrivateConnection(request: r, options: o)
        })
    }

    public func getPrivateConnection(
      request: GetPrivateConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.PrivateConnection {
      try await self._intercept(
        request: request,
        options: options,
        name: "getPrivateConnection",
        action: {
          (r: GetPrivateConnectionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMwareEngineV1.PrivateConnection
          in
          return try await self.inner.getPrivateConnection(request: r, options: o)
        })
    }

    public func listPrivateConnections(
      request: ListPrivateConnectionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ListPrivateConnectionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listPrivateConnections",
        action: {
          (r: ListPrivateConnectionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMwareEngineV1.ListPrivateConnectionsResponse
          in
          return try await self.inner.listPrivateConnections(request: r, options: o)
        })
    }

    public func updatePrivateConnection(
      request: UpdatePrivateConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updatePrivateConnection",
        action: {
          (r: UpdatePrivateConnectionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updatePrivateConnection(request: r, options: o)
        })
    }

    public func deletePrivateConnection(
      request: DeletePrivateConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deletePrivateConnection",
        action: {
          (r: DeletePrivateConnectionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deletePrivateConnection(request: r, options: o)
        })
    }

    public func listPrivateConnectionPeeringRoutes(
      request: ListPrivateConnectionPeeringRoutesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ListPrivateConnectionPeeringRoutesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listPrivateConnectionPeeringRoutes",
        action: {
          (r: ListPrivateConnectionPeeringRoutesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMwareEngineV1.ListPrivateConnectionPeeringRoutesResponse
          in
          return try await self.inner.listPrivateConnectionPeeringRoutes(request: r, options: o)
        })
    }

    public func grantDnsBindPermission(
      request: GrantDnsBindPermissionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "grantDnsBindPermission",
        action: {
          (r: GrantDnsBindPermissionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.grantDnsBindPermission(request: r, options: o)
        })
    }

    public func getDnsBindPermission(
      request: GetDnsBindPermissionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.DnsBindPermission {
      try await self._intercept(
        request: request,
        options: options,
        name: "getDnsBindPermission",
        action: {
          (r: GetDnsBindPermissionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMwareEngineV1.DnsBindPermission
          in
          return try await self.inner.getDnsBindPermission(request: r, options: o)
        })
    }

    public func revokeDnsBindPermission(
      request: RevokeDnsBindPermissionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "revokeDnsBindPermission",
        action: {
          (r: RevokeDnsBindPermissionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.revokeDnsBindPermission(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "setIamPolicy",
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIamPolicy",
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "testIamPermissions",
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }
  }
}
