// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax

extension Clients {
  protocol VmwareEngineStub: Sendable {
    func listPrivateClouds(
      request: ListPrivateCloudsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ListPrivateCloudsResponse

    func getPrivateCloud(
      request: GetPrivateCloudRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.PrivateCloud

    func createPrivateCloud(
      request: CreatePrivateCloudRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updatePrivateCloud(
      request: UpdatePrivateCloudRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deletePrivateCloud(
      request: DeletePrivateCloudRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func undeletePrivateCloud(
      request: UndeletePrivateCloudRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listClusters(
      request: ListClustersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ListClustersResponse

    func getCluster(
      request: GetClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.Cluster

    func createCluster(
      request: CreateClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateCluster(
      request: UpdateClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteCluster(
      request: DeleteClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listNodes(
      request: ListNodesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ListNodesResponse

    func getNode(
      request: GetNodeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.Node

    func listExternalAddresses(
      request: ListExternalAddressesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ListExternalAddressesResponse

    func fetchNetworkPolicyExternalAddresses(
      request: FetchNetworkPolicyExternalAddressesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.FetchNetworkPolicyExternalAddressesResponse

    func getExternalAddress(
      request: GetExternalAddressRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ExternalAddress

    func createExternalAddress(
      request: CreateExternalAddressRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateExternalAddress(
      request: UpdateExternalAddressRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteExternalAddress(
      request: DeleteExternalAddressRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listSubnets(
      request: ListSubnetsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ListSubnetsResponse

    func getSubnet(
      request: GetSubnetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.Subnet

    func updateSubnet(
      request: UpdateSubnetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listExternalAccessRules(
      request: ListExternalAccessRulesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ListExternalAccessRulesResponse

    func getExternalAccessRule(
      request: GetExternalAccessRuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ExternalAccessRule

    func createExternalAccessRule(
      request: CreateExternalAccessRuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateExternalAccessRule(
      request: UpdateExternalAccessRuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteExternalAccessRule(
      request: DeleteExternalAccessRuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listLoggingServers(
      request: ListLoggingServersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ListLoggingServersResponse

    func getLoggingServer(
      request: GetLoggingServerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.LoggingServer

    func createLoggingServer(
      request: CreateLoggingServerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateLoggingServer(
      request: UpdateLoggingServerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteLoggingServer(
      request: DeleteLoggingServerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listNodeTypes(
      request: ListNodeTypesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ListNodeTypesResponse

    func getNodeType(
      request: GetNodeTypeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.NodeType

    func showNsxCredentials(
      request: ShowNsxCredentialsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.Credentials

    func showVcenterCredentials(
      request: ShowVcenterCredentialsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.Credentials

    func resetNsxCredentials(
      request: ResetNsxCredentialsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func resetVcenterCredentials(
      request: ResetVcenterCredentialsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getDnsForwarding(
      request: GetDnsForwardingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.DnsForwarding

    func updateDnsForwarding(
      request: UpdateDnsForwardingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getNetworkPeering(
      request: GetNetworkPeeringRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.NetworkPeering

    func listNetworkPeerings(
      request: ListNetworkPeeringsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ListNetworkPeeringsResponse

    func createNetworkPeering(
      request: CreateNetworkPeeringRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteNetworkPeering(
      request: DeleteNetworkPeeringRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateNetworkPeering(
      request: UpdateNetworkPeeringRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listPeeringRoutes(
      request: ListPeeringRoutesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ListPeeringRoutesResponse

    func createHcxActivationKey(
      request: CreateHcxActivationKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listHcxActivationKeys(
      request: ListHcxActivationKeysRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ListHcxActivationKeysResponse

    func getHcxActivationKey(
      request: GetHcxActivationKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.HcxActivationKey

    func getNetworkPolicy(
      request: GetNetworkPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.NetworkPolicy

    func listNetworkPolicies(
      request: ListNetworkPoliciesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ListNetworkPoliciesResponse

    func createNetworkPolicy(
      request: CreateNetworkPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateNetworkPolicy(
      request: UpdateNetworkPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteNetworkPolicy(
      request: DeleteNetworkPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listManagementDnsZoneBindings(
      request: ListManagementDnsZoneBindingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ListManagementDnsZoneBindingsResponse

    func getManagementDnsZoneBinding(
      request: GetManagementDnsZoneBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ManagementDnsZoneBinding

    func createManagementDnsZoneBinding(
      request: CreateManagementDnsZoneBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateManagementDnsZoneBinding(
      request: UpdateManagementDnsZoneBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteManagementDnsZoneBinding(
      request: DeleteManagementDnsZoneBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func repairManagementDnsZoneBinding(
      request: RepairManagementDnsZoneBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createVmwareEngineNetwork(
      request: CreateVmwareEngineNetworkRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateVmwareEngineNetwork(
      request: UpdateVmwareEngineNetworkRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteVmwareEngineNetwork(
      request: DeleteVmwareEngineNetworkRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getVmwareEngineNetwork(
      request: GetVmwareEngineNetworkRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.VmwareEngineNetwork

    func listVmwareEngineNetworks(
      request: ListVmwareEngineNetworksRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ListVmwareEngineNetworksResponse

    func createPrivateConnection(
      request: CreatePrivateConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getPrivateConnection(
      request: GetPrivateConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.PrivateConnection

    func listPrivateConnections(
      request: ListPrivateConnectionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ListPrivateConnectionsResponse

    func updatePrivateConnection(
      request: UpdatePrivateConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deletePrivateConnection(
      request: DeletePrivateConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listPrivateConnectionPeeringRoutes(
      request: ListPrivateConnectionPeeringRoutesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.ListPrivateConnectionPeeringRoutesResponse

    func grantDnsBindPermission(
      request: GrantDnsBindPermissionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getDnsBindPermission(
      request: GetDnsBindPermissionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMwareEngineV1.DnsBindPermission

    func revokeDnsBindPermission(
      request: RevokeDnsBindPermissionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}
